### PR TITLE
OCM-8693 | test: Add tag/untag role/policy functions

### PR DESCRIPTION
**Pull request by yuwang-RH**
OCM-8693 | test: Add tag/untag role/policy functions
Testing is passed on my local.

### CODE REVIEW

**Comment by yuwang-RH** [comment]
@xueli181114 Could you help review this PR?Thanks.

**Comment by yuwang-RH** [comment]
@ciaranRoche @robpblake Could you help take a look and approve it if there is no problem?Thanks.

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Pull request merged**
