### PR TITLE
OCM-12919 | chore:  Migrates config package for ocm tools

### PR DESCRIPTION
**Pull request by iamkirkbater**
This PR aims to migrate the `pkg/config` contents from openshift-online/ocm-cli to ocm-common.

This was tested by removing the `pkg/ocm/config` directory from `openshift-online/ocm-cli`, running a sed command to replace all instances of config, and adding the following lines to go.mod. I then built the CLI tool, saw no build errors, ran a login and spot checked a few other commands with no issues.

```bash
find cmd -type f -print0 | xargs -0 gsed -i s#github.com/openshift-online/ocm-cli/pkg/config#github.com/openshift-online/ocm-common/pkg/ocm/config#
```

^ Note this uses `gsed` because I'm on a Mac, linux users will just need `sed`

```go
require github.com/openshift-online/ocm-common v0.0.13
replace github.com/openshift-online/ocm-common v0.0.13 => /Users/kbater/Projects/openshift-online/ocm-com
mon
```

Additional testing was performed with migrating openshift/osdctl#632 to use these packages, using a similar require/replace methodology in the go.mod to test against this package locally.

### CODE REVIEW

**Comment by xueli181114** [comment]
@iamkirkbater Do you mind to fix the failures?

**Comment by xueli181114** [comment]
@iamkirkbater too many commits. You have to run `git rebase -i HEAD~n` to squash the commits

**Comment by iamkirkbater** [comment]
Rebased.

**Pull request merged**
